//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCenter.Service.Message.Assessment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AssessmentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssessmentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProCenter.Service.Message.Assessment.AssessmentResources", typeof(AssessmentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Last Sent:.
        /// </summary>
        public static string AssessmentSummary_EmailSentDate {
            get {
                return ResourceManager.GetString("AssessmentSummary_EmailSentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: .
        /// </summary>
        public static string AssessmentSummary_LastModifiedTime {
            get {
                return ResourceManager.GetString("AssessmentSummary_LastModifiedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Not Sent..
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {0},&lt;/p&gt;&lt;p&gt;A time-sensitive assessment has been created, and is ready for you to access through your PRO Center Account. Please click on the link provided below to log in to your account, and begin your assessment.&lt;/p&gt;&lt;p&gt;&lt;a href=&apos;{1}&apos;&gt;PRO Center Login&lt;/a&gt;&lt;/p&gt;                                         &lt;p&gt;Sincerely, &lt;br /&gt;PRO Center Team&lt;/p&gt; &lt;p&gt;&lt;i&gt;&lt;b&gt;Disclaimer:&lt;/b&gt;To help keep your account secure, never share or disclose your password to anyone you do not trust via email, phone or by any other means. I [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SelfAdministrableAssessmentCreatedEmailBody {
            get {
                return ResourceManager.GetString("SelfAdministrableAssessmentCreatedEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRO Center Assessment.
        /// </summary>
        public static string SelfAdministrableAssessmentCreatedEmailSubject {
            get {
                return ResourceManager.GetString("SelfAdministrableAssessmentCreatedEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
    }
}
