//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCenter.Mvc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserControlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserControlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProCenter.Mvc.Resources.UserControlResources", typeof(UserControlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username/password..
        /// </summary>
        internal static string ChangePasswordResponseCode_InvalidCredentials {
            get {
                return ResourceManager.GetString("ChangePasswordResponseCode_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password cannot be changed. The email address for this user account is associated with multiple user accounts..
        /// </summary>
        internal static string ChangePasswordResponseCode_MultipleAccount {
            get {
                return ResourceManager.GetString("ChangePasswordResponseCode_MultipleAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find your account by email..
        /// </summary>
        internal static string ChangePasswordResponseCode_NoAccount {
            get {
                return ResourceManager.GetString("ChangePasswordResponseCode_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password updated sucessfully..
        /// </summary>
        internal static string ChangePasswordResponseCode_Succeed {
            get {
                return ResourceManager.GetString("ChangePasswordResponseCode_Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error, please contact your administrator if you continue to see this message..
        /// </summary>
        internal static string LockUnLockResponseCode_Error {
            get {
                return ResourceManager.GetString("LockUnLockResponseCode_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string LockUnLockResponseCode_Success {
            get {
                return ResourceManager.GetString("LockUnLockResponseCode_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account does not exist, please contact your administrator..
        /// </summary>
        internal static string LockUnLockResponseCode_UnknownAccount {
            get {
                return ResourceManager.GetString("LockUnLockResponseCode_UnknownAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string ResetPasswordResponseCode_Error {
            get {
                return ResourceManager.GetString("ResetPasswordResponseCode_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string ResetPasswordResponseCode_Success {
            get {
                return ResourceManager.GetString("ResetPasswordResponseCode_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Account.
        /// </summary>
        internal static string ResetPasswordResponseCode_UnknownAccount {
            get {
                return ResourceManager.GetString("ResetPasswordResponseCode_UnknownAccount", resourceCulture);
            }
        }
    }
}
