//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCenter.Mvc.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProCenter.Mvc.Views.Shared.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administer Assessment Now.
        /// </summary>
        public static string AdministerAssessmentNowButton {
            get {
                return ResourceManager.GetString("AdministerAssessmentNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to change password or logou.
        /// </summary>
        public static string ChangePasswordMessage {
            get {
                return ResourceManager.GetString("ChangePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder: {0} should complete assessment {1} by {2:M/d/yyyy}.
        /// </summary>
        public static string ConmpleteAssessmentMessage {
            get {
                return ResourceManager.GetString("ConmpleteAssessmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajax request aborted..
        /// </summary>
        public static string ErrorAjaxAborted {
            get {
                return ResourceManager.GetString("ErrorAjaxAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error:\n.
        /// </summary>
        public static string ErrorInternalServerError {
            get {
                return ResourceManager.GetString("ErrorInternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.\nParsing JSON Request failed..
        /// </summary>
        public static string ErrorJsonParser {
            get {
                return ResourceManager.GetString("ErrorJsonParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are offline!!\n Please Check Your Network..
        /// </summary>
        public static string ErrorOffline {
            get {
                return ResourceManager.GetString("ErrorOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Time out..
        /// </summary>
        public static string ErrorRequestTimeout {
            get {
                return ResourceManager.GetString("ErrorRequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error:\n.
        /// </summary>
        public static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested URL not found..
        /// </summary>
        public static string ErrorUrlNotFound {
            get {
                return ResourceManager.GetString("ErrorUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site contains certain features and services that require javascript in order to function properly. Please enable javascript in your browser and try again..
        /// </summary>
        public static string JavaScriptNoEnabled {
            get {
                return ResourceManager.GetString("JavaScriptNoEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out Now.
        /// </summary>
        public static string LogOutNow {
            get {
                return ResourceManager.GetString("LogOutNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Interval.
        /// </summary>
        public static string NotificationInterval {
            get {
                return ResourceManager.GetString("NotificationInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time.
        /// </summary>
        public static string OneTime {
            get {
                return ResourceManager.GetString("OneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring.
        /// </summary>
        public static string Recurring {
            get {
                return ResourceManager.GetString("Recurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string RejectButton {
            get {
                return ResourceManager.GetString("RejectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports Center.
        /// </summary>
        public static string ReportsCenter {
            get {
                return ResourceManager.GetString("ReportsCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Assessment.
        /// </summary>
        public static string SearchAssessment {
            get {
                return ResourceManager.GetString("SearchAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Patient.
        /// </summary>
        public static string SearchPatient {
            get {
                return ResourceManager.GetString("SearchPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Expiration.
        /// </summary>
        public static string SessionExpiration {
            get {
                return ResourceManager.GetString("SessionExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session is about to expire warning.
        /// </summary>
        public static string SessionExprirationWarning {
            get {
                return ResourceManager.GetString("SessionExprirationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session will expire in another .
        /// </summary>
        public static string SessionIsGoingToExpire {
            get {
                return ResourceManager.GetString("SessionIsGoingToExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Notification.
        /// </summary>
        public static string SetNotificationButton {
            get {
                return ResourceManager.GetString("SetNotificationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since:.
        /// </summary>
        public static string Since {
            get {
                return ResourceManager.GetString("Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skip to main content.
        /// </summary>
        public static string SkipToMain {
            get {
                return ResourceManager.GetString("SkipToMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay Connected.
        /// </summary>
        public static string StayConnected {
            get {
                return ResourceManager.GetString("StayConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Admin.
        /// </summary>
        public static string SystemAdmin {
            get {
                return ResourceManager.GetString("SystemAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab.
        /// </summary>
        public static string Tab {
            get {
                return ResourceManager.GetString("Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Assessments.
        /// </summary>
        public static string TotalAssessments {
            get {
                return ResourceManager.GetString("TotalAssessments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because patient {0} scored {1} on {2} it is recommended that the patient takes {3}..
        /// </summary>
        public static string WorkflowMessage {
            get {
                return ResourceManager.GetString("WorkflowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
