//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCenter.Mvc.Views.ReportsCenter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportsCenter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportsCenter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProCenter.Mvc.Views.ReportsCenter.ReportsCenter", typeof(ReportsCenter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment.
        /// </summary>
        public static string Assessment {
            get {
                return ResourceManager.GetString("Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft.
        /// </summary>
        public static string HeightUnit1 {
            get {
                return ResourceManager.GetString("HeightUnit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string HeightUnit2 {
            get {
                return ResourceManager.GetString("HeightUnit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Run Date.
        /// </summary>
        public static string LastRunDate {
            get {
                return ResourceManager.GetString("LastRunDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed Reminders.
        /// </summary>
        public static string MissedReminder {
            get {
                return ResourceManager.GetString("MissedReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Calendar.
        /// </summary>
        public static string MyCalendar {
            get {
                return ResourceManager.GetString("MyCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an assessment first to search questions..
        /// </summary>
        public static string NoAssessmentWarning {
            get {
                return ResourceManager.GetString("NoAssessmentWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site contains certain features and services that require javascript in order to function properly. Please enable javascript in your browser and try again..
        /// </summary>
        public static string NoScript {
            get {
                return ResourceManager.GetString("NoScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Run Reports.
        /// </summary>
        public static string RecentReports {
            get {
                return ResourceManager.GetString("RecentReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports Builder.
        /// </summary>
        public static string ReportBuilderButtonTitle {
            get {
                return ResourceManager.GetString("ReportBuilderButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports Center.
        /// </summary>
        public static string ReportCenterTitle {
            get {
                return ResourceManager.GetString("ReportCenterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Name.
        /// </summary>
        public static string ReportName {
            get {
                return ResourceManager.GetString("ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Template Name.
        /// </summary>
        public static string ReportTemplateNameColumn {
            get {
                return ResourceManager.GetString("ReportTemplateNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Templates.
        /// </summary>
        public static string ReportTemplates {
            get {
                return ResourceManager.GetString("ReportTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Report Name.
        /// </summary>
        public static string SavedReportNameColumn {
            get {
                return ResourceManager.GetString("SavedReportNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Reports.
        /// </summary>
        public static string SavedReports {
            get {
                return ResourceManager.GetString("SavedReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search all missed reminders, recently run reports, saved reports, report templates and reminders.
        /// </summary>
        public static string SearchDescription {
            get {
                return ResourceManager.GetString("SearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all reports.
        /// </summary>
        public static string ShowAllReports {
            get {
                return ResourceManager.GetString("ShowAllReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my reports.
        /// </summary>
        public static string ShowMyReports {
            get {
                return ResourceManager.GetString("ShowMyReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
