//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCenter.Service.Message.Report {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Report {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Report() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProCenter.Service.Message.Report.Report", typeof(Report).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Range.
        /// </summary>
        public static string AgeRange {
            get {
                return ResourceManager.GetString("AgeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment.
        /// </summary>
        public static string Assessment {
            get {
                return ResourceManager.GetString("Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Score Over Time.
        /// </summary>
        public static string AssessmentScoreOverTime {
            get {
                return ResourceManager.GetString("AssessmentScoreOverTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Risk?.
        /// </summary>
        public static string AtRisk {
            get {
                return ResourceManager.GetString("AtRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is at risk.
        /// </summary>
        public static string IsAtRisk {
            get {
                return ResourceManager.GetString("IsAtRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Completed Assessment.
        /// </summary>
        public static string NotCompletedAssessment {
            get {
                return ResourceManager.GetString("NotCompletedAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of .
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Score Range.
        /// </summary>
        public static string PatientScoreRange {
            get {
                return ResourceManager.GetString("PatientScoreRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients with Specific Response.
        /// </summary>
        public static string PatientsWithSpecificResponse {
            get {
                return ResourceManager.GetString("PatientsWithSpecificResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients with Specific Response Across Assessments.
        /// </summary>
        public static string PatientsWithSpecificResponseAcrossAssessments {
            get {
                return ResourceManager.GetString("PatientsWithSpecificResponseAcrossAssessments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Range.
        /// </summary>
        public static string RiskRange {
            get {
                return ResourceManager.GetString("RiskRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Range.
        /// </summary>
        public static string ScoreRange {
            get {
                return ResourceManager.GetString("ScoreRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Period.
        /// </summary>
        public static string TimePeriod {
            get {
                return ResourceManager.GetString("TimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string ToLowerCase {
            get {
                return ResourceManager.GetString("ToLowerCase", resourceCulture);
            }
        }
    }
}
