//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCenter.Domain.Nih {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NihHealthBehaviorsAssessmentReportStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NihHealthBehaviorsAssessmentReportStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProCenter.Domain.Nih.NihHealthBehaviorsAssessmentReportStrings", typeof(NihHealthBehaviorsAssessmentReportStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Alcohol:.
        /// </summary>
        internal static string AlcoholLabel {
            get {
                return ResourceManager.GetString("AlcoholLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answers suggest you are a heavy drinker and this is bad for your health..
        /// </summary>
        internal static string AlcoholRecommendationFourOrMoreTimes {
            get {
                return ResourceManager.GetString("AlcoholRecommendationFourOrMoreTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answers suggest you drink more than is healthy for you. This is a concern..
        /// </summary>
        internal static string AlcoholRecommendationOneToThreeTimes {
            get {
                return ResourceManager.GetString("AlcoholRecommendationOneToThreeTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reported that you have had more than 4 drinks a day {0}.
        /// </summary>
        internal static string AlcoholReported {
            get {
                return ResourceManager.GetString("AlcoholReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and that you {0} fall asleep during the daytime.
        /// </summary>
        internal static string AndFallAsleepDuringDay {
            get {
                return ResourceManager.GetString("AndFallAsleepDuringDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and you had little interest or pleasure in doing things for.
        /// </summary>
        internal static string AndLittleInterestInDoingThings {
            get {
                return ResourceManager.GetString("AndLittleInterestInDoingThings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and that you never fall asleep during the daytime.
        /// </summary>
        internal static string AndNeverFallAsleepDuringDay {
            get {
                return ResourceManager.GetString("AndNeverFallAsleepDuringDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and that you have used smokeless tobacco.
        /// </summary>
        internal static string AndYouHaveUseedSmokelessTobacco {
            get {
                return ResourceManager.GetString("AndYouHaveUseedSmokelessTobacco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Anxiety:.
        /// </summary>
        internal static string AnxietyLabel {
            get {
                return ResourceManager.GetString("AnxietyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answers suggest that you are experiencing significant anxiety..
        /// </summary>
        internal static string AnxietyRecommendation {
            get {
                return ResourceManager.GetString("AnxietyRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (please check for accuracy):.
        /// </summary>
        internal static string CheckForAccuracy {
            get {
                return ResourceManager.GetString("CheckForAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear .
        /// </summary>
        internal static string Dear {
            get {
                return ResourceManager.GetString("Dear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reported that you felt down, depressed or hopeless for.
        /// </summary>
        internal static string DepressedOrDown {
            get {
                return ResourceManager.GetString("DepressedOrDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Depression:.
        /// </summary>
        internal static string DepressionLabel {
            get {
                return ResourceManager.GetString("DepressionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answers suggest that you may be depressed..
        /// </summary>
        internal static string DepressionRecommendation {
            get {
                return ResourceManager.GetString("DepressionRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your diet includes more fast food than is healthy for you. This is a concern..
        /// </summary>
        internal static string DietFastFoodRecommendationFourOrMoreTimes {
            get {
                return ResourceManager.GetString("DietFastFoodRecommendationFourOrMoreTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You eat very little fast food. This is great and very good for your health!.
        /// </summary>
        internal static string DietFastFoodRecommendationLessThanOneTime {
            get {
                return ResourceManager.GetString("DietFastFoodRecommendationLessThanOneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You eat lots of fruits and vegetables. This is great and very good for your health!.
        /// </summary>
        internal static string DietFruitsVegetablesRecommendationFiveOrMoreTimes {
            get {
                return ResourceManager.GetString("DietFruitsVegetablesRecommendationFiveOrMoreTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t eat very many fruits and vegetables.  This is a concern..
        /// </summary>
        internal static string DietFruitsVegetablesRecommendationTwoOrLessTimes {
            get {
                return ResourceManager.GetString("DietFruitsVegetablesRecommendationTwoOrLessTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Diet:.
        /// </summary>
        internal static string DietLabel {
            get {
                return ResourceManager.GetString("DietLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You diet may be putting you at risk for a number of health problems..
        /// </summary>
        internal static string DietRecommendationSummary {
            get {
                return ResourceManager.GetString("DietRecommendationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reported that you had {0} fast food meal(s) or snack(s) last week, {1} fruits/vegetables per day, and {2} soda/sugar sweetended drink(s) per day..
        /// </summary>
        internal static string DietReported {
            get {
                return ResourceManager.GetString("DietReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t drink very many sodas or sugary drinks.  This is great and very good for your health!.
        /// </summary>
        internal static string DietSodaSugarRecommendationLessThanOne {
            get {
                return ResourceManager.GetString("DietSodaSugarRecommendationLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You drink more sodas and sugary drinks than is good for your health.  This is a concern..
        /// </summary>
        internal static string DietSodaSugarRecommendationThreeOrMore {
            get {
                return ResourceManager.GetString("DietSodaSugarRecommendationThreeOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Drug Use:.
        /// </summary>
        internal static string DrugUseLabel {
            get {
                return ResourceManager.GetString("DrugUseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You seem to be having problems with drug misuse.  This is a concern..
        /// </summary>
        internal static string DrugUseRecommendationFourOrMoreTimes {
            get {
                return ResourceManager.GetString("DrugUseRecommendationFourOrMoreTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answers suggest you may be having problems with drug misuse..
        /// </summary>
        internal static string DrugUseRecommendationOneToThreeTimes {
            get {
                return ResourceManager.GetString("DrugUseRecommendationOneToThreeTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reported that you did not use illegal drugs or prescription medication for non-medical reasons in the past year..
        /// </summary>
        internal static string DrugUseReportedNever {
            get {
                return ResourceManager.GetString("DrugUseReportedNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reported that you did use illegal drugs or prescription medication for non-medical reasons in the past year..
        /// </summary>
        internal static string DrugUseReportedOther {
            get {
                return ResourceManager.GetString("DrugUseReportedOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It would be helpful to increase your physical activity. Our goal for you is at least 150 total minutes of exercise per week..
        /// </summary>
        internal static string Exercise150 {
            get {
                return ResourceManager.GetString("Exercise150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is a good amount.  200 total minutes of exercise per week is considered standard..
        /// </summary>
        internal static string Exercise200 {
            get {
                return ResourceManager.GetString("Exercise200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Exercise:.
        /// </summary>
        internal static string ExerciseLabel {
            get {
                return ResourceManager.GetString("ExerciseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You report getting about {0} minutes of exercise {1} time(s) per week..
        /// </summary>
        internal static string ExerciseSummary {
            get {
                return ResourceManager.GetString("ExerciseSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please follow up with your doctor..
        /// </summary>
        internal static string FollowUpWithDoctor {
            get {
                return ResourceManager.GetString("FollowUpWithDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • General Health:.
        /// </summary>
        internal static string GeneralHealthLabel {
            get {
                return ResourceManager.GetString("GeneralHealthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You said that in general your health was {0}.
        /// </summary>
        internal static string GeneralHealthReported {
            get {
                return ResourceManager.GetString("GeneralHealthReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations for Topics to Discuss with Your Health Care Provider: .
        /// </summary>
        internal static string Header_RecommendationsForTopics {
            get {
                return ResourceManager.GetString("Header_RecommendationsForTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the past 30 days.
        /// </summary>
        internal static string InThePast30Days {
            get {
                return ResourceManager.GetString("InThePast30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the past week.
        /// </summary>
        internal static string InThePastWeek {
            get {
                return ResourceManager.GetString("InThePastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your health care provider would like to work with you on improving your health. Please consider the following topics as you have a discusssion about your health issues on your next visit:.
        /// </summary>
        internal static string Label_HealthCareProviderRecommendations {
            get {
                return ResourceManager.GetString("Label_HealthCareProviderRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reported feeling nervous, anxious or on edge for.
        /// </summary>
        internal static string NervousOrAnxious {
            get {
                return ResourceManager.GetString("NervousOrAnxious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You report getting no excersise each week.
        /// </summary>
        internal static string NoExercise {
            get {
                return ResourceManager.GetString("NoExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reported that you did not feel nervous, anxious or on edge.
        /// </summary>
        internal static string NoStressOrAnxious {
            get {
                return ResourceManager.GetString("NoStressOrAnxious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and not being able to stop or control worrying for.
        /// </summary>
        internal static string NotAbleToStopOrControlWorry {
            get {
                return ResourceManager.GetString("NotAbleToStopOrControlWorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reported that you did not feel down, depressed or hopeless..
        /// </summary>
        internal static string NotDepressedOrDown {
            get {
                return ResourceManager.GetString("NotDepressedOrDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obesity can lead to a number of health problems such as diabetes, heart disease and high blood pressure..
        /// </summary>
        internal static string ObesityWarning {
            get {
                return ResourceManager.GetString("ObesityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or had little interest or pleasure in doing things.
        /// </summary>
        internal static string OrLittleInterestInDoingThings {
            get {
                return ResourceManager.GetString("OrLittleInterestInDoingThings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to over the past 2 weeks..
        /// </summary>
        internal static string Past2Weeks {
            get {
                return ResourceManager.GetString("Past2Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You answered that the most important thing leading to your poor health status is.
        /// </summary>
        internal static string PoorHealthFactors {
            get {
                return ResourceManager.GetString("PoorHealthFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Sleep:.
        /// </summary>
        internal static string SleepLabel {
            get {
                return ResourceManager.GetString("SleepLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and where able to stop or control worrying.
        /// </summary>
        internal static string StopOrControlWorry {
            get {
                return ResourceManager.GetString("StopOrControlWorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high.
        /// </summary>
        internal static string StressHigh {
            get {
                return ResourceManager.GetString("StressHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Stress:.
        /// </summary>
        internal static string StressLabel {
            get {
                return ResourceManager.GetString("StressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to low.
        /// </summary>
        internal static string StressLow {
            get {
                return ResourceManager.GetString("StressLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reported having a {0} amount of stress - a score of {1} on a scale from 0 to 10.
        /// </summary>
        internal static string StressReported {
            get {
                return ResourceManager.GetString("StressReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderate.
        /// </summary>
        internal static string StrressModerate {
            get {
                return ResourceManager.GetString("StrressModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for filling out the questionnaire. Here is a summary of your results and some suggestions for topics to cover with your health care provider..
        /// </summary>
        internal static string SummaryHeader {
            get {
                return ResourceManager.GetString("SummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Results for .
        /// </summary>
        internal static string SummaryResultsFor {
            get {
                return ResourceManager.GetString("SummaryResultsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a concern..
        /// </summary>
        internal static string ThisIsAConcern {
            get {
                return ResourceManager.GetString("ThisIsAConcern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times.
        /// </summary>
        internal static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Tobacco:.
        /// </summary>
        internal static string TobaccoLabel {
            get {
                return ResourceManager.GetString("TobaccoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reported a weight of {0} lbs and a height of {1}.
        /// </summary>
        internal static string WeightHeight {
            get {
                return ResourceManager.GetString("WeightHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Weight:.
        /// </summary>
        internal static string WeightLabel {
            get {
                return ResourceManager.GetString("WeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        internal static string WeightRecommendationNormal {
            get {
                return ResourceManager.GetString("WeightRecommendationNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excess weight can lead to a number of health problems such as diabetes, heart disease and high blood pressure..
        /// </summary>
        internal static string WeightRecommendationOverweight {
            get {
                return ResourceManager.GetString("WeightRecommendationOverweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You mentioned that you do not snore.
        /// </summary>
        internal static string YouDoNotSnore {
            get {
                return ResourceManager.GetString("YouDoNotSnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reported that you do not use tobacco. Congratulations. That is one of the best things you can do for your health.
        /// </summary>
        internal static string YouDoNotUseTobacco {
            get {
                return ResourceManager.GetString("YouDoNotUseTobacco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You mentioned that you do snore.
        /// </summary>
        internal static string YouDoSnore {
            get {
                return ResourceManager.GetString("YouDoSnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reported that you have smoked.
        /// </summary>
        internal static string YouHaveSmoked {
            get {
                return ResourceManager.GetString("YouHaveSmoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reported that you have used smokeless tobacco.
        /// </summary>
        internal static string YouHaveUsedSmokelessTobacco {
            get {
                return ResourceManager.GetString("YouHaveUsedSmokelessTobacco", resourceCulture);
            }
        }
    }
}
