//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCenter.Domain.Nida {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NidaWorkflowPatientSummaryReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NidaWorkflowPatientSummaryReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProCenter.Domain.Nida.NidaWorkflowPatientSummaryReport", typeof(NidaWorkflowPatientSummaryReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Amber {
            get {
                return ResourceManager.GetString("Amber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discuss readiness to change your behaviors..
        /// </summary>
        internal static string AssessReadinessToChange {
            get {
                return ResourceManager.GetString("AssessReadinessToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will feel healthier if you refrain from using drugs..
        /// </summary>
        internal static string BenefitOfDrugAbstinentFeedback {
            get {
                return ResourceManager.GetString("BenefitOfDrugAbstinentFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please schedule an appointment(s) to address the following:.
        /// </summary>
        internal static string FollowUpHeader {
            get {
                return ResourceManager.GetString("FollowUpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A follow up appointment for {0} to monitor progress.
        /// </summary>
        internal static string FollowUpVisit {
            get {
                return ResourceManager.GetString("FollowUpVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mental health conditions (mood disorders, anxiety, trauma/stress reaction).
        /// </summary>
        internal static string MentalHealthCondition {
            get {
                return ResourceManager.GetString("MentalHealthCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug treatment History.
        /// </summary>
        internal static string ObtainDrugTreatmentHistory {
            get {
                return ResourceManager.GetString("ObtainDrugTreatmentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobacco and Alcohol use.
        /// </summary>
        internal static string ObtainTobaccoAlcoholHistory {
            get {
                return ResourceManager.GetString("ObtainTobaccoAlcoholHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please immediately report to the onsite treatment program..
        /// </summary>
        internal static string OnsiteOpiodeTreatment {
            get {
                return ResourceManager.GetString("OnsiteOpiodeTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please immediately report to the off-site treatment program.
        /// </summary>
        internal static string OpioidDependenceOffSiteTreatment {
            get {
                return ResourceManager.GetString("OpioidDependenceOffSiteTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please immediately report to the onsite treatment program.
        /// </summary>
        internal static string OpioidDependenceOnSiteTreatment {
            get {
                return ResourceManager.GetString("OpioidDependenceOnSiteTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please consider taking advantage of the following resources:.
        /// </summary>
        internal static string PatientResourceHeader {
            get {
                return ResourceManager.GetString("PatientResourceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations on leading a healthy lifestyle..
        /// </summary>
        internal static string PositiveFeedback {
            get {
                return ResourceManager.GetString("PositiveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preventive health screenings (e.g. HIV, hepatitis, Sexually Transmitted Infections, etc.).
        /// </summary>
        internal static string PreventiveScreenings {
            get {
                return ResourceManager.GetString("PreventiveScreenings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please consider abstaining from drug use..
        /// </summary>
        internal static string RecommendCessation {
            get {
                return ResourceManager.GetString("RecommendCessation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please immediately report to the off-site treatement program..
        /// </summary>
        internal static string ReferalOpiodeTreatment {
            get {
                return ResourceManager.GetString("ReferalOpiodeTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact our recommended treatment specialist/program regarding treatment..
        /// </summary>
        internal static string ReferralForFurtherAssessment {
            get {
                return ResourceManager.GetString("ReferralForFurtherAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIDA Patient Summary.
        /// </summary>
        internal static string ReportName {
            get {
                return ResourceManager.GetString("ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review your current list of medications.
        /// </summary>
        internal static string ReviewCurrentMedication {
            get {
                return ResourceManager.GetString("ReviewCurrentMedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please schedule an appointment to address the following:.
        /// </summary>
        internal static string ScheduleSummary {
            get {
                return ResourceManager.GetString("ScheduleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexual Transmitted Infections Screening.
        /// </summary>
        internal static string SexualTransmittedInjectionScreening {
            get {
                return ResourceManager.GetString("SexualTransmittedInjectionScreening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You scored a {0} on the DAST-10 and the following was reported:.
        /// </summary>
        internal static string SummaryHeader {
            get {
                return ResourceManager.GetString("SummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} use of {0}.
        /// </summary>
        internal static string SummaryItems {
            get {
                return ResourceManager.GetString("SummaryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please explore participation with the recommended Support Group(s)..
        /// </summary>
        internal static string SupportGroups {
            get {
                return ResourceManager.GetString("SupportGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a urine specimen to the Lab we recomended..
        /// </summary>
        internal static string UrineDrugScreen {
            get {
                return ResourceManager.GetString("UrineDrugScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.S. Department of Health &amp; Human Services (www.hhs.gov).
        /// </summary>
        internal static string UsDepartmentHealthAndHumanServices {
            get {
                return ResourceManager.GetString("UsDepartmentHealthAndHumanServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a release for or discuss with your physician your:.
        /// </summary>
        internal static string UseTreatmentHistoryHeader {
            get {
                return ResourceManager.GetString("UseTreatmentHistoryHeader", resourceCulture);
            }
        }
    }
}
