//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinktecture.IdentityServer.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SecurityQuestions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityQuestions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thinktecture.IdentityServer.Web.Resources.SecurityQuestions", typeof(SecurityQuestions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was your first job?.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the model of your first car?.
        /// </summary>
        public static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the middle name of your oldest child?.
        /// </summary>
        public static string Question10 {
            get {
                return ResourceManager.GetString("Question10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your oldest sibling&apos;s middle name?.
        /// </summary>
        public static string Question11 {
            get {
                return ResourceManager.GetString("Question11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was your childhood phone number including area code? (e.g., 000-000-0000).
        /// </summary>
        public static string Question12 {
            get {
                return ResourceManager.GetString("Question12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your oldest cousin&apos;s first and last name?.
        /// </summary>
        public static string Question13 {
            get {
                return ResourceManager.GetString("Question13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the name of your first stuffed animal?.
        /// </summary>
        public static string Question14 {
            get {
                return ResourceManager.GetString("Question14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In what city or town did your mother and father meet?.
        /// </summary>
        public static string Question15 {
            get {
                return ResourceManager.GetString("Question15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the last name of your third grade teacher?.
        /// </summary>
        public static string Question16 {
            get {
                return ResourceManager.GetString("Question16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In what city does your nearest sibling live?.
        /// </summary>
        public static string Question17 {
            get {
                return ResourceManager.GetString("Question17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your maternal grandmother&apos;s maiden name?.
        /// </summary>
        public static string Question18 {
            get {
                return ResourceManager.GetString("Question18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In what city or town was your first job?.
        /// </summary>
        public static string Question19 {
            get {
                return ResourceManager.GetString("Question19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the name of your first pet?.
        /// </summary>
        public static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the name of the place your wedding reception was held?.
        /// </summary>
        public static string Question20 {
            get {
                return ResourceManager.GetString("Question20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the name of a college you applied to but didn&apos;t attend?.
        /// </summary>
        public static string Question21 {
            get {
                return ResourceManager.GetString("Question21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In What city was your Mother born?.
        /// </summary>
        public static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In What city was your Father born?.
        /// </summary>
        public static string Question4 {
            get {
                return ResourceManager.GetString("Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was your high school mascot?.
        /// </summary>
        public static string Question5 {
            get {
                return ResourceManager.GetString("Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With What company was your first job?.
        /// </summary>
        public static string Question6 {
            get {
                return ResourceManager.GetString("Question6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the name of your first roommate?.
        /// </summary>
        public static string Question7 {
            get {
                return ResourceManager.GetString("Question7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was your favorite high school subject?.
        /// </summary>
        public static string Question8 {
            get {
                return ResourceManager.GetString("Question8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What street did you live on in third grade?.
        /// </summary>
        public static string Question9 {
            get {
                return ResourceManager.GetString("Question9", resourceCulture);
            }
        }
    }
}
