//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCenter.Mvc.Views.Portal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Portal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Portal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProCenter.Mvc.Views.Portal.Portal", typeof(Portal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows all assessments displayed in order of most recent. Double click header bar to expand and see more details..
        /// </summary>
        public static string GuideAllAssessments {
            get {
                return ResourceManager.GetString("GuideAllAssessments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar shows up-coming assessments to be completed. Double click header bar to expand and see more details..
        /// </summary>
        public static string GuideCalendar {
            get {
                return ResourceManager.GetString("GuideCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to manage your account or log out..
        /// </summary>
        public static string GuideChangePassword {
            get {
                return ResourceManager.GetString("GuideChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See messages, current activities and summary of assessment completion..
        /// </summary>
        public static string GuideCurrentActivities {
            get {
                return ResourceManager.GetString("GuideCurrentActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows most recent reports. Double click header bar to expand and see more details..
        /// </summary>
        public static string GuideRecentReports {
            get {
                return ResourceManager.GetString("GuideRecentReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an incomplete assessment: {0}.
        /// </summary>
        public static string IncompleteAssessment {
            get {
                return ResourceManager.GetString("IncompleteAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows all assessments displayed in order of most recent. Double click header bar to expand and see more details..
        /// </summary>
        public static string InfoButtonAllAssessments {
            get {
                return ResourceManager.GetString("InfoButtonAllAssessments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders show up-coming assessments to be completed. Double click a reminder to see more details..
        /// </summary>
        public static string InfoButtonCalendar {
            get {
                return ResourceManager.GetString("InfoButtonCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This panel contains the messages, alerts, and the assessments you need to complete..
        /// </summary>
        public static string InfoButtonCurrentActivities {
            get {
                return ResourceManager.GetString("InfoButtonCurrentActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your assessment reports are displayed here; to see the reports in detail please double click header bar..
        /// </summary>
        public static string InfoButtonRecentReports {
            get {
                return ResourceManager.GetString("InfoButtonRecentReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site contains certain features and services that require javascript in order to function properly. Please enable javascript in your browser and try again..
        /// </summary>
        public static string NoScript {
            get {
                return ResourceManager.GetString("NoScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Dashboard.
        /// </summary>
        public static string PortalDashboardTitle {
            get {
                return ResourceManager.GetString("PortalDashboardTitle", resourceCulture);
            }
        }
    }
}
